### ISSUE TITLE
How to implement this as a library for arduino?

### ISSUE THREAD

**Issue by EuphoriaCelestial** [Noxet/grain128a#1]
As the title, am looking for a proper way to make this project become a Arduino library.
Am just get started with both Arduino and crypto, please help

**Comment by Noxet** [comment]
You do not need a library, just use the c and h files in your project. Note that this is a debug version of the cipher. You need to remove the prints etc. if you want to use it in Arduino. I also use malloc in the code, which might not be optimal in an Arduino. Either remove those, and replace with static allocation or have a look at [this](https://www.nongnu.org/avr-libc/user-manual/malloc.html).

For a better implementation, you should look at my other repo, Grain-128AEAD. There is an optimized version which is way faster. You might have to tweak the static buffers so they fit an Arduino.

p.s.
Out of curiosity, what are you planning on doing with this stream cipher?

**Comment by EuphoriaCelestial** [comment]
do you have Arduino example code for this your cipher?
am using this as a demonstrate for my class

**Comment by Noxet** [comment]
> do you have Arduino example code for this your cipher?
> am using this as a demonstrate for my class

Read my previous answer.
